// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.AddressBook.Postgres;

#nullable disable

namespace Service.AddressBook.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("addressbook")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.AddressBook.Domain.Models.AddressBookRecord", b =>
                {
                    b.Property<string>("ContactId")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("Bic")
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerClientId")
                        .HasColumnType("text");

                    b.Property<bool>("ReceiveApprovalGranted")
                        .HasColumnType("boolean");

                    b.Property<int>("TransfersCount")
                        .HasColumnType("integer");

                    b.HasKey("ContactId");

                    b.HasIndex("OwnerClientId", "Iban")
                        .IsUnique();

                    b.HasIndex("OwnerClientId", "Name")
                        .IsUnique();

                    b.HasIndex("OwnerClientId", "Nickname")
                        .IsUnique();

                    b.ToTable("addressbook", "addressbook");
                });
#pragma warning restore 612, 618
        }
    }
}
